version: '3.9'

services:
  postgres:
    container_name: movie-mingle-db
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    network_mode: "host"

  backend:
      container_name: movie-mingle-backend
      image: movie-mingle-backend-image
      build:
        context: movie-mingle-backend
        dockerfile: Dockerfile
      network_mode: "host"
      depends_on:
        - postgres

  frontend:
    container_name: movie-mingle
    image: movie-mingle-image
    build:
      context: movie-mingle
      dockerfile: Dockerfile
    network_mode: "host"

